name: isolate_server
description: Implements isolate stream,server,client, ... shelf isolate, webworker
dependencies:
  browser: any
  http_client:
    git:
      url: git://github.com/tercen/http_client.git
      ref: "1.0"
  logging: any
  shelf: any
